changes

diff --git a/create-image-backup b/create-image-backup
--- a/create-image-backup
+++ b/create-image-backup
@@ -1,8 +1,24 @@
 #!/bin/bash
+# Setup script error handling see https://disconnected.systems/blog/another-bash-strict-mode for details
+set -uo pipefail
+trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+IFS=$'\n\t'
 
+# Ensure we are root
+if [[ $EUID -ne 0 ]]; then
+    echo "This script must be run as root" 1>&2
+    exit 1
+fi
+
+# Some useful constants
 mount="mnt" # Local directory to mount the image (automatically created/delete as needed)
 script="setup" # Local setup script to run inside the image
 
+size="${1:-2G}"
+image="${2:-raspbian.img}"
+
+# Tasks to run when the shell exits for any reason, unmount the image and
+# general cleanup
 cleanup() {
     [[ -f "${mount}/tmp/${script}" ]] && rm "${mount}/tmp/${script}"
     if [[ -d "${mount}" ]]; then
@@ -23,7 +39,9 @@ unzip 2018-11-13-raspbian-stretch-lite.zip
 mv 2018-11-13-raspbian-stretch-lite.img raspbian.img
 ls
 
-
+#sudo kpartx -v -a raspbian.img
+#losetup --find --show "${image}"
+#fallocate -l "${size}" "${image}"
 loopdev=$(losetup -fP --show raspbian.img)
 lsblk
 bootdev=/dev/loop0p1
@@ -36,7 +54,10 @@ mount "${rootdev}" "${mount}"
 [ ! -d "${mount}/boot" ] && mkdir "${mount}/boot"
 mount "${bootdev}" "${mount}/boot"
 ls ${mount}
+# Install archlinuxarm to the image
+#tar -xpf "${rpi_tar}" -C ${mount} 2> >(grep -v "Ignoring unknown extended header keyword")
 
+# Copy our installation script to the mount so it can be run in the chroot
 install -Dm755 "${script}" "${mount}/tmp/${script}"
 
 # Prep the chroot
